#cloud-config

package_update: true
package_upgrade: true

packages:
  - apt-show-versions
  - bc
  - bison
  - build-essential
  - chrony
  - flex
  - gcc
  - git
  - libelf-dev
  - libssl-dev
  - mc
  - mc
  - pv
  - python3
  - python3-apt
  - python3-apt
  - python3-minimal
  - python3-pip
  - python3-pip
  - python3-setuptools
  - sysstat
  - vim
  - vim-nox
  - virtualenv
  - virtualenvwrapper
  - xz

power_state:
  delay: "now"
  mode: reboot
  message: Rebooting
  condition: True
