#cloud-config

package_update: true
package_upgrade: true

packages:
  - python3
  - python3-setuptools
  - python3-apt
  - python3-pip
  - mc
  - vim
  - sysstat

power_state:
  delay: "now"
  mode: reboot
  message: Rebooting
  condition: True
