---
- import_playbook: bootstrap.yml

- hosts: all
  become: yes
  vars_files:
    - vars/tmpfs_glusterfs.yml
  vars:
    - glusterfs_ppa_version: "6"
      
  # install glusterfs-{server, client}
  roles:
    - geerlingguy.glusterfs

  tasks:
    - include_tasks: tasks/setup_tmpfs.yml
    - include_tasks: tasks/create_gluster_vol.yml
    - include_tasks: tasks/mount_gluster.yml
