---
# Use cloud-config.yml to bootstrap
- hosts: all
  become: yes
  vars_files:
    - vars/tmpfs_glusterfs.yml
      
  tasks:
    - include_tasks: tasks/setup_tmpfs.yml
    - include_tasks: tasks/create_gluster_vol.yml
    - include_tasks: tasks/mount_gluster.yml
