---
- hosts: gserver
  become: yes
  vars_files:
    - vars/tmpfs_dirs.yml
    - vars/tmpfs_glusterfs_dirs.yml
  vars:
    - glusterfs_ppa_version: "6"
      
  # install glusterfs-{server, client}
  roles:
    - geerlingguy.glusterfs

  tasks:
    - include_tasks: tasks/setup_mnt.yml
    - include_tasks: tasks/mnt_tmpfs.yml
    - include_tasks: tasks/create_gluster_vol.yml
