---
# Set target to the "tag" or the set of machines that you want to cluster
# Usage: ansible-playbook -i digitalocean.py -e target=zram zram_glusterfs.yml
- hosts: '{{ target }}'
  become: yes
  vars_files:
    - vars/zram_glusterfs.yml
  vars:
    - glusterfs_ppa_version: "8"

  # install glusterfs-{server, client}
  roles:
    - geerlingguy.glusterfs

  tasks:
    - include_tasks: tasks/setup_zram_glusterfs.yml
