---
- hosts: gserver
  become: yes
  vars_files:
    - vars/zram.yml
  vars:
    - glusterfs_ppa_version: "6"

  # install glusterfs-{server, client}
  roles:
    - geerlingguy.glusterfs

  tasks:
    - include_tasks: tasks/load_zram.yml
    - include_tasks: tasks/create_zram_dev.yml
    - include_tasks: tasks/mkfs_zram.yml
    - include_tasks: tasks/mnt_zram.yml
    - include_tasks: tasks/create_gluster_vol.yml
