---
- name: Create glusterfs volume
  gluster_volume:
    state: present
    name: "{{ glusterfs_vol_name }}"
    bricks: "{{ glusterfs_brick_dir }}"
    cluster: "{{ ansible_play_hosts }}"
    force: true
  run_once: true
