---
- name: Create glusterfs volume
  gluster_volume:
    state: present
    name: "{{ glusterfs_vol_name }}"
    bricks: "{{ glusterfs_brick_dir }}"
    cluster:
      # Figure out how to use groups['all']
      # List of IPs
    force: true
  run_once: true
