---
- name: Debug mkfs a zram device
  debug:
    msg: "zram = {{ zram_dev}} zram_fstype = {{ zram_fstype }}"

- name: mkfs a zram device
  filesystem:
    dev: /dev/{{ zram_dev }}
    fstype: "{{ zram_fstype }}"
    force: yes
