---
- name: Setup mount points
  become: yes
  file:
    path: "{{ tmpfs_mount_dir }}"
    state: directory
    mode: 0755

- name: Mount tmpfs
  become: yes
  mount:
    path: "{{ tmpfs_mount_dir }}"
    src: "tmpfs"
    fstype: "tmpfs"
    opts: "size={{ tmpfs_size }}"
    state: mounted

