---
- name: Setup brick dir
  file:
    path: "{{ glusterfs_brick_dir }}"
    state: directory
    mode: 0755

- name: Create glusterfs volume
  gluster_volume:
    state: present
    name: "{{ glusterfs_vol_name }}"
    bricks: "{{ glusterfs_brick_dir }}"
    cluster: "{{ ansible_play_hosts }}"
    force: true
  run_once: true

- name: Create mount point
  file:
    path: "{{ glusterfs_mount_dir }}"
    state: directory
    mode: 0755

- name: Mount gluster volume
  mount:
    fstype: glusterfs
    opts: defaults,_netdev
    path: "{{ glusterfs_mount_dir }}"
    src: "{{ groups['all'][0] }}:/{{ glusterfs_vol_name }}"
    state: mounted
